name: Deploy to server 6

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
      
    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log
          
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log
        
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test
          path: test.log
        