name: Deploy clase 3.1

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Install redi cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Test redis
        run: redis-cli -h localhost -p 6379 ping

      - name: Print variable v2
        run: echo "${{ secrets.JESS_SECRET }}"

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'